{% set version = "1.2.0" %}

package:
  name: pamela
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pamela/pamela-{{ version }}.tar.gz
  sha256: 0ea6e2a99dded8c7783a4a06f2d31f5bdcad894d79101e8f09322e387a34aacf

build:
  number: 0
  skip: True  # [py<38 or win]
  script: pip install --no-deps --ignore-installed --no-build-isolation .

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools_scm
  run:
    - python

test:
  requires:
    - pip
  imports:
    - pamela
  commands:
    - pip check

about:
  home: https://github.com/minrk/pamela
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: PAM interface using ctypes
  description: "Pamela: yet another Python wrapper for PAM"
  doc_url: https://github.com/minrk/pamela/blob/main/README.md
  dev_url: https://github.com/minrk/pamela

extra:
  recipe-maintainers:
    - minrk
