appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DEniW2SAYDxfnYaKXaUHW13vLUeEw0DvBVo1fpbhxtU6vm7RCjqu1R9tK3DsHtH1JLjKdPjcWd7ww3zo6MX33lqPqsc25/ROTiFBXeeWJl3KRickUif7A9Xi0LBVmObJhOFEtQv3/VJaszLuxbkKOPf0nckjzAMOYL9iQL3rLZIeGiq1XA8BqhB/VYuaIUrI2o4k0J7MjwjTbT7Un598EJTP1kpEHkpuwB8i/asvnoNfTasIaThHe52aZ0SRx3dCv8f5xsqVl6OTnsIRSRymaqXjtrRjNtKy/PA6s965vKv5BMgsCkNI4yz8QOpFjcNbY+kjclaaGZoSnVOUvACFfKaariTZipdW8t1/s9grj1l+k4dtIwIY7+0UYtGSZ3rmq7K3XWWePByJ31AiM7cHZGJTGySljMDZB0JId4uz9fnzyx9f5DaB5Lgo6tZVSHHZF1DmuuM97lPvWuN25dWU8Qd9wBcIDjj+v8Y4ZaXzqXdjMmyh98ZzQgwdyeHEPOiLptcnaFJkDDWFhikDLDjzww3eGy4SITSxzdh37Qbwflv/VOWG69VfQf2+cwhs127spGxes70HzZjaI5XB8ulKLvZwmtLwiuKGqvJnDMyitFRvJlHY4RSSf47lgp65jMruws0h4Su7DwtL1iB3i9w6SlCoMroiHuTrhs5KY4+Z3pU=}
conda_forge_output_validation: true
