travis:
  secure:
    BINSTAR_TOKEN: qQHBZl5lVMEBisyl/ix09Nbn2TvOubDW4YwU72b7e8D1evxkmOk4DQTNP28J6qQzCd9Y4s3wF/vO163D7UkV/5yKFsUmSJx90i+o2Smsp9FMw8QpHNztGZwifr4IPZBrG7HjPM5IAB4k/GIq65grRiv4iKkQ7eZtIG0mPMUX7WI3MC94+MrIcls5NT53UpdbpLhAomir4CDKxzlmAOZBUrne1hmdJWMy8mBOKJsq7CxxpdA1y2az/IHXdCiM1U75f6h9hPCcI4P0TBtDOt1LbZ6ZiD1aYI+sxITkFgu9Otn66uHoQCpVtCPkIgaRIahOTPH15/I9ZZIACB5DEYv4B8/BTCaorMbQHoINQ+iYBG7+koGQj0b9pcEDLitsHm3QIJbOdfeuy+WcElVcVI36L2ms3tIYDTPs+wPgeZY+PcGZfHNBBzxFTT5/0nvjXznyjEXbqYL4E9144nuu9Dwh+eV+KCyLB7rMW61uaMUNz6DSFVr7WRDPzWJgs9xOcf60QySPmN94fHiSUFEcPHsiHS6R/bvItlghOizCKCTIn+gifG0oayMc/NoAtc8g/F4oTdJbiOZpDz0FsTGMHfCbf3YJebHtxVV/Q6+f+waqaNHk/xjzWTvu+xgM/nq79HbERSSlLKostjF8lczCHrkOGKULgxxlnTgObAPXHescmlw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
