travis:
  secure:
    BINSTAR_TOKEN: lmpPcmLasGl8xOQhNuqtIx+8XLhvLdJs16VhUlLjfw8lnxjHJDx2pdM7hMn/RJCFQLimc7XV6oi/ZJCVj0bNICblATwrKwARYEulo/L4z5CqjQ1GvaZFHrMrbVZ3WgwsHyLcBTh0nm/cOHnDjno+C/QZOV6OCV1mxLWs4y0ejmCQ4zCvyluADZ98/OnVkYtUxLQwRCR8L+F0F1msxYL4VTVv3vRMfaERG43oht0TT/mO1Vgl7Jv4H7tXiH1n+Y/douUgSrrf0qZeYxbHq4IcYBdoOOrl1feB9lnUJcJDExAvkQzbf2p7+UpvQxy1uaSmYE8yJfY4jO/CFW3gfQJSM9xGNh0XqB5OIPJ03O4aprDZPev4Eyr+NWol6e010GOclK3S4vmr6S7p+VgcvdshyLE0ft8T1SjjAfW9jtXvbNQeIBThKkVcCPT+w5rw9hE00wfvMFoBp8HBR86TDTBodtLr6h35CDYAlVNDsp3DNAiEUDCcIZ7KxShEKRrriT+ByD4FEnLCzhMMIYp3fcdhqdm6ntu2Dpf/jePGQ4+O3cNuwNKqUMZKXx9f6Nk45L1YliIXihlGywUdW5D0QjE1WFNZS7MCcpAJhhjEMg+auZRTy5fxhFoghO1sfnABkIoI2IXb5+kW4sYFxMSU8/q8xfWyX4ELtbs3gbmlo9KLOyc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
